[package]
name = "wascc-actor-hello-http"
version = "0.0.1"
authors = ["Kit Ewbank <Christopher.Ewbank@capitalone.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wascc-actor = "0.1.1"

[profile.release]
# Optimize for small code size
opt-level = "s"
